import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useEffect } from "react";
import Hero1 from "../../public/homepage/hero/hero-1.jpeg";
import Hero2 from "../../public/homepage/hero/hero-2.jpeg";
import RaybanLogo from "../../public/brands/rayban.jpeg";
import LeiaLogo from "../../public/brands/leia.jpeg";
import GucciLogo from "../../public/brands/gucci.jpeg";
import OakleyLogo from "../../public/brands/oakley.jpeg";
import Carousel from "~/components/ui/carousel/Carousel";
import Image from "next/image";
import Link from "next/link";

const heroCarouselData = [
  {
    image: Hero1,
  },
  {
    image: Hero2,
  },
  {
    image: Hero1,
  },
];

const heroBrandsLeft = [RaybanLogo, LeiaLogo, GucciLogo, OakleyLogo];

const trends = [
  {
    image: "https://static1.lenskart.com/media/desktop/img/Sep21/image179.png",
    link: "/",
    name: "Round",
  },
  {
    image: "https://static1.lenskart.com/media/desktop/img/Sep21/cateeye.jpg",
    link: "/",
    name: "Cat-Eye",
  },
  {
    image:
      "https://static1.lenskart.com/media/desktop/img/Sep21/clubmaster.jpg",
    link: "/",
    name: "Clubmaster",
  },
  {
    image: "https://static1.lenskart.com/media/desktop/img/Sep21/trans.jpg",
    link: "/",
    name: "Transparent",
  },
  {
    image: "https://static1.lenskart.com/media/desktop/img/Sep21/blend.jpg",
    link: "/",
    name: "Blend Edit",
  },
  {
    image: "https://static1.lenskart.com/media/desktop/img/Sep21/clipon.jpg",
    link: "/",
    name: "Clip On",
  },
  {
    image: "https://static1.lenskart.com/media/desktop/img/Sep21/blend.jpg",
    link: "/",
    name: "Blend Edit",
  },
];

const Home: NextPage = () => {
  const { data, status, update } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex w-full flex-col gap-20 px-[min(5vh,5vw)] py-14">
        {/* HERO SECTION */}
        <div className="mx-auto grid w-[100%] grid-cols-[1fr_9fr_1fr] overflow-hidden rounded-lg shadow-primary-sm max-[600px]:grid-cols-1">
          <div className="flex h-full w-full flex-col items-center justify-between gap-[min(2vh,2vw)]  p-[min(2vh,2vw)] max-[600px]:flex-row">
            {heroBrandsLeft.map((image) => (
              <div className="h-[min(10vh,10vw)] w-[min(10vh,10vw)] overflow-hidden rounded-full shadow-primary-xsm">
                <Image
                  src={image}
                  alt="Brand Image"
                  className="h-full w-full object-cover"
                  width={200}
                  height={200}
                />
              </div>
            ))}
          </div>
          <Carousel data={heroCarouselData} height="min(50vh,50vw)" />
          <div className="flex h-full w-full flex-col  items-center justify-between gap-[min(2vh,2vw)] p-[min(2vh,2vw)] max-[600px]:flex-row">
            {heroBrandsLeft.map((image) => (
              <div className="h-[min(10vh,10vw)] w-[min(10vh,10vw)] overflow-hidden rounded-full shadow-primary-xsm">
                <Image
                  src={image}
                  alt="Brand Image"
                  className="h-full w-full object-cover"
                  width={200}
                  height={200}
                />
              </div>
            ))}
          </div>
        </div>
        {/* TREND SECTION */}
        <div className="flex w-full flex-col gap-8">
          <h3 className="text-3xl font-medium">Trends</h3>
          <div className="flex gap-[min(2vh,2vw)]">
            {trends.map((trend) => (
              <Link
                href={trend.link}
                className="flex w-full flex-col overflow-hidden rounded-lg shadow-primary-sm"
              >
                <Image
                  src={trend.image}
                  alt={trend.name}
                  className="h-[80%] w-full object-contain"
                  width={200}
                  height={200}
                />
                <div className="flex grow items-center justify-center py-0.5">
                  <span className="">{trend.name}</span>
                </div>
              </Link>
            ))}
          </div>
        </div>
        {/* TRENDING SUNGLASSES SECTION*/}
        <div className="flex h-80 w-full flex-col gap-8">
          <h3 className="text-3xl font-medium">Top Sunglasses</h3>
          <div className="flex gap-8"></div>
        </div>
      </main>
    </>
  );
};

export default Home;
