import Head from "next/head";
import React from "react";

const ProductsPage = () => {
  return (
    <>
      <Head>
        <title>Products Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <div>ProductsPage</div>;
    </>
  );
};

export default ProductsPage;
